In [57]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
    

In [58]:
df= pd.read_csv("Iris.csv")

In [59]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [60]:
from sklearn.preprocessing import LabelEncoder

l=LabelEncoder()

df['Species']=l.fit_transform(df['Species'])
print(df)


      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]


In [61]:
y=df['Species']

x=df.drop(columns=['Species','Id'])

In [62]:
print(x)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


In [63]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25, random_state=0)

In [64]:
from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()

model=nb.fit(x_train, y_train)

In [65]:
y_pred=model.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score
print("Accuracy Score: ", accuracy_score(y_test,y_pred))

Accuracy Score:  1.0


In [67]:
from sklearn.metrics import confusion_matrix

confusion_matrix=confusion_matrix(y_test,y_pred)

print(confusion_matrix)

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]


In [68]:
def eval(cm, c):
    row_sum=np.sum(cm, axis=0)
    col_sum=np.sum(cm, axis=1)
    
    tp=cm[c][c]
    fp=col_sum[c]-cm[c][c]
    fn=row_sum[c]-cm[c][c]
    tn=np.sum(cm)-tp-fp-fn
    
    accuracy= (tp+tn)/(tp+tn+fp+fn)
    precision=tp/(tp+fp)
    recall=tp/(tp+fn)
    
    return tp,fp,fn,tn,accuracy,precision,recall


In [69]:
tp_setosa,fp_setosa,fn_setosa,tn_setosa,accuracy,precision,recall=eval(confusion_matrix,0)

In [70]:
print("For Class Setosa")
print("TP : ", tp_setosa)
print("FP : ", fp_setosa)
print("FN : ", fn_setosa)
print("TN : ", tn_setosa)
print("Precision : ", precision)
print("Recall : ", recall)
print("Accuarcy : ", accuracy)

For Class Setosa
TP :  13
FP :  0
FN :  0
TN :  25
Precision :  1.0
Recall :  1.0
Accuarcy :  1.0
